<Tarefa>
    Button:
        text: 'Procure o Arquivo'
        size_hint: [.3, .1]
        pos_hint: {"x": .35, "y": .9}
        on_press: root.mudatexto()
        id: bt1

    Label:
        text: 'abc'
        size_hint: [.2, .2]
        pos_hint: {"x": .0, "y": .4}
        id: lb1
#FloatLayout:
#    FileChooserIconView:
#        text: 'Procure o Arquivo'
#        size_hint: [1, .5]
#        pos_hint: {"x": 0, "y": .3}
#        id: filechooser


