<Prog>
    Button:
        text: 'Procure o Arquivo'
        size_hint: [.3, .1]
        pos_hint: {"x": .35, "y": .9}
        on_press: root.mudatexto()
        id: bt1
    FloatLayout:
        id: fl2
        size_hint: [1, .7]
        pos_hint: {"x": .0, "y": .2}


#FloatLayout:
#    FileChooserIconView:
#        text: 'Procure o Arquivo'
#        size_hint: [1, .5]
#        pos_hint: {"x": 0, "y": .3}
#        id: filechooser


